### PR TITLE
Initial Travis CI setup.

### PR DESCRIPTION
**Pull request by parkr**
@spraints, @mastahyeti is it OK if I add this repo to Travis?
Would be nice to have CI check our changes automatically.

### CODE REVIEW

**Comment by mastahyeti** [comment]
No objections from me.

**Comment by parkr** [comment]
Only one failing test, believe it or not!

```text
expected ["\x92\xA6stdout\xB6STDOUT from somewhere\n\x92\xA6return\xA6raboof", "\x92\xA6return\xA6raboof\x92\xA6stdout\xB6STDOUT from somewhere\n"] to include "\x92\xA6stdout\xC4\x16STDOUT from somewhere\n\x92\xA6return\xA6raboof"
```

@spraints, how did you settle on this expectation? It looks like a low-level change here–how important is the content-surrounding bytes?

**Comment by spraints** [comment]
> It looks like a low-level change here–how important is the content-surrounding bytes?

It's pretty important. It looks like it's maybe UTF-8 encoding the string (changing `\xB6` to `\xC4\x16`)? I don't think messagepack will be able to handle that correctly.

**Comment by spraints** [comment]
>     expected ["\x92\xA6stdout\xB6STDOUT from somewhere\n\x92\xA6return\xA6raboof",
>       "\x92\xA6return\xA6raboof\x92\xA6stdout\xB6STDOUT from somewhere\n"]
>       to include "\x92\xA6stdout\xC4\x16STDOUT from somewhere\n\x92\xA6return\xA6raboof"

I'm still not sure why `\xB6` is changing into `\xC4\x16`. This is almost a UTF-8 thing... `B6` is `1011 0110` in binary. If you need a UTF-8 encoding of that, you would use the 11-bit form. (I'm looking at the [utf-8 wikipedia entry](https://en.wikipedia.org/wiki/UTF-8#Description).) This form is `110xxxxx 10xxxxxx`, filled in it's `1100 0010 1011 0110`, which is `C4 B6`, so not quite the same.

I've tried forcing a bunch of encodings to ascii/binary, and printing encodings in a few places, but I haven't found anything. Maybe it would be better to use the protocol class to decode the message, and just look at the decoded forms, rather than comparing a manually encoded form?

**Comment by parkr** [comment]
Abandoning.

**Pull request closed without merging**
