### PR TITLE
Bump msgpack gem

### PR DESCRIPTION
**Pull request by sbryant**
The gem requires a version bump for ruby 2.4.0 support.

### CODE REVIEW

**Comment by parkr** [comment]
Seems fine to me on the surface. How do the tests look to you locally, @sbryant?

**Comment by sbryant** [comment]
> Seems fine to me on the surface. How do the tests look to you locally, @sbryant?

On 🔥 😿 

@spraints not sure how to run the tests properly, can you help me out here?

Are all docker calls supposed to be stubbed or am I getting lucky with `excon` errors: 

```ShellSession
 Excon::Error::Socket:
       No such file or directory - connect(2) for /path/to/socket (Errno::ENOENT)
```

**Comment by spraints** [comment]
> Are all docker calls supposed to be stubbed or am I getting lucky with excon errors:

I think the tests use docker. I'm out today and tomorrow, but I'll add this to my list of things to check on after that.

**Comment by spraints** [comment]
> I think the tests use docker.

The tests do [build a docker image](https://github.com/github/hoosegow/blob/fbe097baec0c0a02b0c1b20e92eede9dbe48683e/Rakefile#L35-L38) and use it. `bundle exec rake spec` isn't working for me, it gets stuck at building the docker image. You can run the specs manually `bundle exec rspec`, and all the ones that try to use docker will fail because they can't talk to docker. IIRC there's pretty good test coverage of the protocol class, at least, without requiring docker.

The pages CI build uses hoosegow+docker, so you could test this by bundling it there and see what happens.

**Comment by sbryant** [comment]
> The pages CI build uses hoosegow+docker, so you could test this by bundling it there and see what happens.

got it working on pages with the help of @parkr. Had to account for some pages specific behavior around integer handling but it seems we're good here.

**Pull request merged**
